### ISSUE TITLE
Line 54 1 app.py

### ISSUE THREAD

**Issue by ajay-marpally** [srijarkoroy/Garbage_Segregation#2]
line 54
          st.info('Hey! The uploaded image has been classified as " {} waste " '.format(labels[np.argmax(prediction[0], axis=-1)]))
                                                                                                                                   ^
SyntaxError: unexpected EOF while parsing

**Comment by srijarkoroy** [comment]
Hey sorry, just add the lines
except:
   pass
The lines might have been deleted before uploading

**Comment by jeevani1275** [comment]
![Screenshot 2022-04-07 115146](https://user-images.githubusercontent.com/88474418/162133408-829db70c-dc12-4999-b302-e2f95c0158bb.jpg)
output not coming
